/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upt.edu.mx.paneles;

/**
 *
 * @author Jose Rene
 */
public class jpnlInicio extends javax.swing.JPanel {

    /**
     * Creates new form panel inicio
     */
    public jpnlInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bienvenido Home-security");
        add(jLabel5);
        jLabel5.setBounds(210, 40, 647, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/icono_LogoInicio.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(230, 160, 300, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/iconoLogoInicio2.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(590, 150, 270, 256);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/iconProteccion.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(430, 450, 100, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/iconNube.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(170, 450, 100, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/iconGraphics.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(860, 450, 110, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt/edu/mx/imagenes/iconWarning.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(650, 440, 100, 100);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Conectado a servicio en la nube");
        add(jLabel8);
        jLabel8.setBounds(130, 530, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Accesos");
        add(jLabel9);
        jLabel9.setBounds(450, 540, 60, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText(" Fallos de tarjeta");
        add(jLabel10);
        jLabel10.setBounds(650, 540, 110, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Estadisticas");
        add(jLabel11);
        jLabel11.setBounds(870, 540, 100, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
