/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upt.edu.mx.paneles;

import com.rene.libraries.builtJtable.Jtable_built;
import static com.rene.libraries.builtJtable.Jtable_built.modeloGenerico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;
import upt.edu.mx.dao.AlarmaDao;
import upt.edu.mx.modelo.Alarma;
import upt.edu.mx.modelo.Usuario;
import upt.edu.mx.rsbuttom.ValidacionesGenericas;
import upt.edu.upt.daoExtends.AlarmaDaoExtends;

/**
 *
 * @author Jose Rene
 */
public class jpnlHistorial<E> extends javax.swing.JPanel {
    AlarmaDao alarmaDao= new AlarmaDao();
    AlarmaDaoExtends alarmaDaoExt= new AlarmaDaoExtends();
    ValidacionesGenericas validacionesGenericas= new ValidacionesGenericas();
    /**
     * Creates new form panel Historial
     */
    public jpnlHistorial() throws Exception {
        initComponents();
        this.RenderChart();
        this.crearModeloTabla();
        this.llenarTabla();
    }
    private int obtenerNumeroAccesos(String _fecha) throws Exception
    {
        try {
//            String fecha=validacionesGenericas.FechaActual();
            int numAccesos=alarmaDaoExt.obtenerNumeroAccesos(Date.valueOf(_fecha));
            return numAccesos;
        } catch (Exception _ex) {
            throw _ex;
        }
    }
    public CategoryDataset createDataset() throws Exception {
        String fechaActual=validacionesGenericas.FechaActual();
        JOptionPane.showMessageDialog(this, fechaActual);
        int anio=validacionesGenericas.obtenerAnio();
        int mes=validacionesGenericas.obtenerMes();
        int dia=validacionesGenericas.obtenerDia();
        int fecha1=obtenerNumeroAccesos(fechaActual);
        int fecha2=obtenerNumeroAccesos(""+anio+"-"+mes+"-"+(dia-1)+"");
        int fecha3=obtenerNumeroAccesos(""+anio+"-"+mes+"-"+(dia-2)+"");
        final double[][] data = new double[][]{
            
            {fecha1,fecha2,fecha3},
        };
        final CategoryDataset dataset = DatasetUtilities.createCategoryDataset(
                "RESULTADO", "", data
        );
        return dataset;
    }
    private void RenderChart() throws Exception {
        try{
        CategoryDataset ds = createDataset();

        JFreeChart chart = ChartFactory.createStackedAreaChart("HISTORIAL DE ACCESOS", "", "", ds);
        chart.setBackgroundPaint(new Color(54, 63, 73));
        chart.setBorderVisible(false);
        chart.setBorderPaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setBackgroundPaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setDomainGridlinePaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setDomainGridlinesVisible(false);
        chart.getCategoryPlot().setOutlinePaint(new Color(54, 63, 73));

        ChartPanel cp = new ChartPanel(chart);
        cp.setBackground(new Color(54, 63, 73));

        jpHistorialGrafics.add(cp, BorderLayout.CENTER);
        jpHistorialGrafics.validate();
        }catch(Exception _ex){
            throw _ex;
        }

    }
    private void llenarTabla() throws Exception
    {
        try 
        {
           Object A[]= null;
           List<Alarma> _object;
           _object=alarmaDaoExt.listarUsuariosAlarma();
            for (int i = 0; i < _object.size(); i++) 
            {
                modeloGenerico.addRow(A);
                modeloGenerico.setValueAt(_object.get(i).getFk_usuario().getNombreUsuario(), i, 0);
                modeloGenerico.setValueAt(_object.get(i).getFk_usuario().getCodigoUsuario(), i, 1);
                modeloGenerico.setValueAt(_object.get(i).getFecha(), i, 2);
                modeloGenerico.setValueAt(_object.get(i).getEstatusAlarma(), i, 3);
                modeloGenerico.setValueAt(_object.get(i).getAccion(), i, 4);
            }
        } catch (Exception _ex) {
            throw _ex;
        }
    }
  private void crearModeloTabla ()
    {
        try 
        {
            String[] array = {"Nombre del usuario","Codigo del usuario","Fecha","Estatus alarma","Accion"};
            Jtable_built jtb = new Jtable_built();
            jtbHistorialAcceso.setModel(jtb.crearModeloGenerico(array, array.length));
        } catch (Exception _ex) 
        {
            throw _ex;
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbHistorialAcceso = new javax.swing.JTable();
        jpHistorialGrafics = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Historial de accesos ");
        add(jLabel5);
        jLabel5.setBounds(330, 10, 420, 30);

        jtbHistorialAcceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbHistorialAcceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbHistorialAcceso.setGridColor(new java.awt.Color(255, 255, 255));
        jtbHistorialAcceso.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbHistorialAcceso);

        add(jScrollPane1);
        jScrollPane1.setBounds(110, 300, 860, 280);
        add(jpHistorialGrafics);
        jpHistorialGrafics.setBounds(110, 50, 850, 220);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpHistorialGrafics;
    private javax.swing.JTable jtbHistorialAcceso;
    // End of variables declaration//GEN-END:variables
}
